name: Generate Release Tag

on:
  push:
    branches:
      - main

jobs:
    create-release:
        if: contains(github.event.head_commit.message, 'release/version/')
        runs-on: ubuntu-latest
        outputs:
            tag-name: ${{ steps.prepare-tag.outputs.tag-name }}
        steps:
        - name: Parse release tag
          id: prepare-tag
          run: |
                commit_message="${{ github.event.head_commit.message }}"
                tag_name=$(echo $commit_message | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
                echo "tag-name=$tag_name" >> "$GITHUB_OUTPUT"

        - name: Checkout branch
          uses: actions/checkout@v4

        - name: Create tag
          run: |
                git tag "${{ steps.prepare-tag.outputs.tag-name }}"

        - name: Push tag to origin
          run: git push origin "${{ steps.prepare-tag.outputs.tag-name }}"
