name: Generate Release Tag

on:
  push:
    branches:
      - main

jobs:
    create-release:
        if: startsWith(github.event.base_ref, 'release/')
        runs-on: ubuntu-latest
        outputs:
            tag-name: ${{ steps.prepare-tag.outputs.tag-name }}
        steps:
        - name: Parse release tag
          id: prepare-tag
          run: |
                branch_name="${{ github.event.base_ref }}"
                tag_name=$(echo $branch_name | sed 's/version\///')
                echo "tag-name=$tag_name" >> $GITHUB_OUTPUT

        - name: Checkout branch
          uses: actions/checkout@v4

        - name: Create tag
          run: |
                git tag "${{ steps.prepare-tag.outputs.tag-name }}"

        - name: Push tag to origin
          run: git push origin "${{ steps.prepare-tag.outputs.tag-name }}"
