name: Merge Main to Staging

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  merge_back:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Generate a token
          id: generate_token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}

        - name: Merge Main to Staging
          env:
            GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          run: |
            curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/merges \
              --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}'\
              --header 'content-type: application/json'\
              --data '{"base":"staging","head":"main","commit_message":"Merging main to staging"}'
